export const ObservationType = {
  'UNDEFINED': 0,
  'FORMAL': 1,
  'INFORMAL': 2
};

export const EvidenceType = {
  'UNDEFINED': 0,
  'ARTIFACT': 1,
  'OBSERVATION_CODED_NOTES': 2,
  'OBSERVATION_CODED_PRECONF_PROMPT_RESPONSE': 3,
  'OBSERVATION_CODED_TOR_PRECONF_SUMMARY': 4,
  'OBSERVATION_CODED_TEE_PRECONF_SUMMARY': 5,  
  'OBSERVATION_CODED_POSTCONF_PROMPT_RESPONSE': 6,
  'OBSERVATION_CODED_TOR_POSTCONF_SUMMARY': 7,
  'OBSERVATION_CODED_TEE_POSTCONF_SUMMARY': 8, 
  'STUDENT_GROWTH_GOAL': 9, 
  'STUDENT_GROWTH_GOAL_SETTING_PROMPT_RESPONSE': 10, 
  'SUMMATIVE_CODED_REFLECTION_PROMPT_RESPONSE': 11,
  'RUBRIC_ROW_NOTE': 12,
  'ARTIFACT_CODED_NOTES': 13,
  'TRAINING_EVIDENCE_SEGMENT': 14
};


export const EvidenceCollectionType = {
  'UNDEFINED': 0,
  'OTHER_EVIDENCE': 1,
  'OBSERVATION': 2,
  'SELF_ASSESSMENT': 3,
  'STUDENT_GROWTH': 4,
  'SUMMATIVE': 5,
  'YEAR_TO_DATE': 10,
  'CALIBRATION_EXERCISE': 11
};

export const PerformanceLevel = {
  'UNDEFINED': 0,
  'UNS': 1,
  'BAS': 2,
  'PRO': 3,
  'DIS': 4
};

export const PlanType = {
  'UNDEFINED': 0,
  'COMPREHENSIVE': 1,
  'FOCUSED': 2,
  'MODIFIED_COMP_2021': 3
};

export const RoleType = {
  'DA': 1,
  'DAM': 2,
  'SPS_CT_TR': 3,
  'DE': 4,
  'DV': 5,
  'DTE': 6,
  'SA': 7,
  'HEAD_PR': 8,
  'PR': 9,
  'TR': 10,
};

export const ThunkState = {
  INIT: 'INIT',
  RUNNING: 'RUNNING',
  COMPLETE: 'COMPLETE',
  FAILED: 'FAILED',
};

export const WorkArea = {
  PR_TR: 'PR_TR',
  PR_ME: 'PR_ME',
  TR_ME: 'TR_ME',
  PR_PR: 'PR_PR',
  DE: 'DE',
  DTE: 'DTE',
  DA_TR: 'DA_TR',
  DA_PR: 'DA_PR',
  DAM_TR: 'DAM_TR',
  DAM_PR: 'DAM_PR',
  SA_TR: 'SA_TR',
  SA_PR: 'SA_PR',
  DV_PR_TR: 'DV_PR_TR',
  DV_PR_PR: 'DV_PR_PR',
  DV_DTE: 'DV_DTE',
  DV_DE: 'DV_DE',
  DV_CT: 'DV_CT'
};

export const WorkState = {
  'UNDEFINED': 0,
  'EVAL_DRAFT': 1,
  'EVAL_READY_FOR_CONFERENCE': 2,
  'EVAL_READY_FOR_FORMAL_RECEIPT': 3,
  'EVAL_RECEIVED': 4,
  'EVAL_LOCKED_SEALED': 5,
  'OBS_IN_PROGRESS_TOR': 6,
  'OBS_LOCKED_TEE_REVIEW': 7,
  'OBS_LOCKED_SEALED': 8,
  'OBS_UNLOCK_REQUEST_TOR': 9,
  'OBS_UNLOCK_REQUEST_TEE': 10,
  'SGBUNDLE_STARTED': 11,
  'SGBUNDLE_PROCESS_SHARED': 12,
  'SGBUNDLE_PROCESS_COMPLETE': 13,
  'SGBUNDLE_UNLOCK_REQUEST_TEE': 14,
  'EVAL_UNLOCK_REQUEST_TOR': 15,
  'EVAL_UNLOCK_REQUEST_TEE': 16,
  'SGBUNDLE_UNLOCK_REQUEST_TOR': 17,
  'PERCEPTION_SURVEY_BUILDING':18,
  'PERCEPTION_SURVEY_CLOSED': 19,
  'PERCEPTION_SURVEY_OPEN': 20,
  'PERCEPTION_SURVEY_COMPLETE': 21
};

export const PerceptionSurveyLevelOfAgreement = {
    'UNDEFINED ': 0,
    'STRONGLY_DISAGREE': 1,
    'DISAGREE': 2,
    'NEITHER': 3,
    'AGREE': 4,
    'STRONGLY_AGREE': 5
};





