const WorkState = {
  'UNDEFINED': 0,
  'EVAL_DRAFT': 1,
  'EVAL_READY_FOR_CONFERENCE': 2,
  'EVAL_READY_FOR_FORMAL_RECEIPT': 3,
  'EVAL_RECEIVED': 4,
  'EVAL_LOCKED_SEALED': 5,
  'OBS_IN_PROGRESS_TOR': 6,
  'OBS_LOCKED_TEE_REVIEW': 7,
  'OBS_LOCKED_SEALED': 8,
  'OBS_UNLOCK_REQUEST_TOR': 9,
  'OBS_UNLOCK_REQUEST_TEE': 10,
  'SGBUNDLE_STARTED': 11,
  'SGBUNDLE_PROCESS_SHARED': 12,
  'SGBUNDLE_PROCESS_COMPLETE': 13,
  'SGBUNDLE_UNLOCK_REQUEST_TEE': 14,
  'EVAL_UNLOCK_REQUEST_TOR': 15,
  'EVAL_UNLOCK_REQUEST_TEE': 16,
  'SGBUNDLE_UNLOCK_REQUEST_TOR': 17,
  'PERCEPTION_SURVEY_BUILDING':18,
  'PERCEPTION_SURVEY_CLOSED': 19,
  'PERCEPTION_SURVEY_OPEN': 20,
  'PERCEPTION_SURVEY_COMPLETE': 21
};

export {
  WorkState
}