// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE.Data;

#nullable disable

namespace SE.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220217183952_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SE.Domain.Entities.Building", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsSchool")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Building", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.DistrictConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("AllowCollectedEvidenceSelectionInFinalReport")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowDownloadReportsSchoolAdmins")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowFocusedComponentScoring")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPackagedEvidenceSelectionInFinalReport")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTeeYTDEvidence")
                        .HasColumnType("bit");

                    b.Property<int>("AssignedCalibrationExerciseSharingType")
                        .HasColumnType("int");

                    b.Property<bool>("CalibrationExercisesModuleEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CriticalAttributesEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CriticalAttributesReferenceOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("DistrictAssignsCalibrationExercises")
                        .HasColumnType("bit");

                    b.Property<bool>("ExemplarVideosModuleEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FinalReportCustomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalReportTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFinalReportConfigDelegated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMidYearReportConfigDelegated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsObsReportConfigDelegated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelfAssessReportConfigDelegated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStudentGrowthReportConfigDelegated")
                        .HasColumnType("bit");

                    b.Property<string>("MidYearReportCustomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidYearReportTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonSummativeScoringEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ObservationReportCustomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservationReportTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReportArchivesPurged")
                        .HasColumnType("bit");

                    b.Property<string>("SelfAssessReportTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfAssessmentReportCustomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SelfAssessmentsModuleEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowArchivedEvaluateeReports")
                        .HasColumnType("bit");

                    b.Property<string>("StudentGrowthGoalSettingReportCustomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentGrowthGoalSettingReportTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummativeCriteriaStmtOfPerfRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("SummativeEvaluationEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SummativeNextYearEvalCycleIsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("SummativeTorFinalRecIsRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkContextId");

                    b.ToTable("DistrictConfiguration", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.Evaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool?>("AutoSubmitAfterReceipt")
                        .HasColumnType("bit");

                    b.Property<bool?>("ByPassReceipt")
                        .HasColumnType("bit");

                    b.Property<string>("ByPassReceiptOverrideComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ByPassSGScores")
                        .HasColumnType("bit");

                    b.Property<int?>("CarryForwardPerformanceLevel")
                        .HasColumnType("int");

                    b.Property<int?>("CarryForwardSchoolYear")
                        .HasColumnType("int");

                    b.Property<bool?>("Complete")
                        .HasColumnType("bit");

                    b.Property<bool?>("ComprehensiveCarryForward")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivateMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DropToPaper")
                        .HasColumnType("bit");

                    b.Property<string>("DropToPaperOverrideComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EOYConfDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EvaluateeFinalReportViewDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvaluateeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("EvaluateePlanType")
                        .HasColumnType("int");

                    b.Property<string>("EvaluateeReflections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EvaluateeReflectionsIsPublic")
                        .HasColumnType("bit");

                    b.Property<long?>("EvaluatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("EvaluatorRecommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EvaluatorScoresShared")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FinalAcknowledgementSentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FinalReportShared")
                        .HasColumnType("bit");

                    b.Property<long?>("FocusedFrameworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FocusedSGFrameworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastYearEvaluateePlanType")
                        .HasColumnType("int");

                    b.Property<string>("LastYearFocusedFrameworkNodeShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastYearFocusedSGframeworkNodeShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LockDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MarkedFinalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MidYearReportsShared")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedCompFocusedFrameworkNode2Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("NextYearEvaluateePlanType")
                        .HasColumnType("int");

                    b.Property<long?>("NextYearFocusedFrameworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NextYearFocusedSGframeworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PerformanceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PromptsTeeSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PromptsTorSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SGScoreOverrideComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("SelfEvalComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SelfEvalCompleteDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SelfEvalSentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SelfEvalShared")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SendFinalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudentGrowthImpactRating")
                        .HasColumnType("int");

                    b.Property<int?>("SuggestedEvaluateePlanType")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedFocusedFrameworkNodeShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuggestedFocusedSGframeworkNodeShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("VisibleToEvaluatee")
                        .HasColumnType("bit");

                    b.Property<int>("WfState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluateeId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("FocusedFrameworkNodeId");

                    b.HasIndex("FocusedSGFrameworkNodeId");

                    b.HasIndex("FrameworkContextId");

                    b.HasIndex("ModifiedCompFocusedFrameworkNode2Id");

                    b.HasIndex("NextYearFocusedFrameworkNodeId");

                    b.HasIndex("NextYearFocusedSGframeworkNodeId");

                    b.ToTable("Evaluation", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidenceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<Guid?>("CodedEvidenceClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("EvidenceCollectionObjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("EvidenceCollectionType")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("int");

                    b.Property<long?>("ObservationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<long>("RubricRowId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserPromptResponseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("RubricRowId");

                    b.HasIndex("UserPromptResponseId");

                    b.ToTable("EvidenceItem", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidencePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("EvidenceCollectionObjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("EvidenceCollectionType")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("int");

                    b.Property<long?>("ObservationId")
                        .HasColumnType("bigint");

                    b.Property<int>("PerformanceLevel")
                        .HasColumnType("int");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<long>("RubricRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("RubricStatement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("RubricRowId");

                    b.ToTable("EvidencePackage", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidencePackageEvidenceItem", b =>
                {
                    b.Property<long>("EvidencePackageId")
                        .HasColumnType("bigint");

                    b.Property<long>("EvidenceItemId")
                        .HasColumnType("bigint");

                    b.HasKey("EvidencePackageId", "EvidenceItemId");

                    b.HasIndex("EvidenceItemId");

                    b.ToTable("EvidencePackageEvidenceItem", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.Framework", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FrameworkTagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Framework", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("DefaultFrameworkId")
                        .HasColumnType("bigint");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("EvaluateeRoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<string>("FrameworkTagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FrameworkViewType")
                        .HasColumnType("int");

                    b.Property<long?>("InstructionalFrameworkId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PrototypeFrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<long>("StateFrameworkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DefaultFrameworkId");

                    b.HasIndex("EvaluateeRoleId");

                    b.HasIndex("InstructionalFrameworkId");

                    b.HasIndex("PrototypeFrameworkContextId");

                    b.HasIndex("StateFrameworkId");

                    b.ToTable("FrameworkContext", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkContextPrototype", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("EvaluateeRoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<string>("FrameworkTagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("InstructionalFrameworkId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<long>("StateFrameworkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EvaluateeRoleId");

                    b.HasIndex("InstructionalFrameworkId");

                    b.HasIndex("StateFrameworkId");

                    b.ToTable("FrameworkContextPrototype", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FrameworkId")
                        .HasColumnType("bigint");

                    b.Property<string>("FrameworkTagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsStudentGrowthAligned")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId");

                    b.ToTable("FrameworkNode", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkNodeRubricRow", b =>
                {
                    b.Property<long>("FrameworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RubricRowId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("FrameworkNodeId", "RubricRowId");

                    b.HasIndex("RubricRowId");

                    b.ToTable("FrameworkNodeRubricRow", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.Observation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvaluateeId")
                        .HasColumnType("bigint");

                    b.Property<int>("EvaluateePlanType")
                        .HasColumnType("int");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("EvaluatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EvaluateeId");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.HasIndex("EvaluatorId");

                    b.ToTable("Observation", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.PerceptionSurvey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CompletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TinyURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PerceptionSurvey", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.PerceptionSurveyStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FrameworkTagName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("RubricRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RubricRowId");

                    b.ToTable("PerceptionSurveyStatement", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EDSName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Role", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.RubricRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameworkTagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsStudentGrowthAligned")
                        .HasColumnType("bit");

                    b.Property<string>("LookFor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookFor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookFor3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookFor4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL1Descriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL2Descriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL3Descriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL4Descriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("Id");

                    b.ToTable("RubricRow", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.SchoolConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("EvaluationSetupDelegated")
                        .HasColumnType("bit");

                    b.Property<long>("FrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<string>("SchoolCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkContextId");

                    b.ToTable("SchoolConfiguration", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.SelfAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluateePlanType")
                        .HasColumnType("int");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("SelfAssessment", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.StudentGrowthGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BundleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("GoalStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ProcessRubricRowId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResultsRubricRowId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudentGrowthGoalBundleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("FrameworkNodeId");

                    b.HasIndex("ProcessRubricRowId");

                    b.HasIndex("ResultsRubricRowId");

                    b.HasIndex("StudentGrowthGoalBundleId");

                    b.ToTable("StudentGrowthGoal", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.StudentGrowthGoalBundle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("EvaluateeEoyconfNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluateeMidConfNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluateeProcessConfNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<string>("EvaluatorEoyconfNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluatorMidConfNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluatorProcessConfNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EvaluatorScoresShared")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GoalSettingConfDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InRevision")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessCompleteDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessSharedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SharingDraft")
                        .HasColumnType("bit");

                    b.Property<int>("WfState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("StudentGrowthGoalBundle", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTPW")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("User", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserBuildingRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BuildingId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBuildingRole", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPrompt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("CreatedAsAdmin")
                        .HasColumnType("bit");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ObservationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Private")
                        .HasColumnType("bit");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromptType")
                        .HasColumnType("int");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("UserPrompts", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPromptGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("CreatedAsAdmin")
                        .HasColumnType("bit");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromptType")
                        .HasColumnType("int");

                    b.Property<long?>("SGFrameworkNodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SchoolCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPromptGroup", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPromptGroupUserPrompt", b =>
                {
                    b.Property<long>("UserPromptGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserPromptId")
                        .HasColumnType("bigint");

                    b.HasKey("UserPromptGroupId", "UserPromptId");

                    b.HasIndex("UserPromptId");

                    b.ToTable("UserPromptGroupUserPrompt", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPromptResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("DefaultAssignment")
                        .HasColumnType("bit");

                    b.Property<long?>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ObservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserPromptId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserPromptId");

                    b.ToTable("UserPromptResponses", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.WorkArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("EvaluateeRoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDistrictAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEvaluatee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEvaluator")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSchoolAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluateeRoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("WorkArea", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.WorkAreaContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BuildingId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameworkContextId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkAreaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FrameworkContextId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkAreaId");

                    b.ToTable("WorkAreaContext", "dbo");
                });

            modelBuilder.Entity("SE.Domain.Entities.DistrictConfiguration", b =>
                {
                    b.HasOne("SE.Domain.Entities.FrameworkContext", "FrameworkContext")
                        .WithMany()
                        .HasForeignKey("FrameworkContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameworkContext");
                });

            modelBuilder.Entity("SE.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("SE.Domain.Entities.User", "Evaluatee")
                        .WithMany()
                        .HasForeignKey("EvaluateeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId");

                    b.HasOne("SE.Domain.Entities.FrameworkNode", "FocusedFrameworkNode")
                        .WithMany()
                        .HasForeignKey("FocusedFrameworkNodeId");

                    b.HasOne("SE.Domain.Entities.FrameworkNode", "FocusedSGFrameworkNode")
                        .WithMany()
                        .HasForeignKey("FocusedSGFrameworkNodeId");

                    b.HasOne("SE.Domain.Entities.FrameworkContext", "FrameworkContext")
                        .WithMany()
                        .HasForeignKey("FrameworkContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.FrameworkNode", "ModifiedCompFocusedFrameworkNode2")
                        .WithMany()
                        .HasForeignKey("ModifiedCompFocusedFrameworkNode2Id");

                    b.HasOne("SE.Domain.Entities.FrameworkNode", "NextYearFocusedFrameworkNode")
                        .WithMany()
                        .HasForeignKey("NextYearFocusedFrameworkNodeId");

                    b.HasOne("SE.Domain.Entities.FrameworkNode", "NextYearFocusedSGframeworkNode")
                        .WithMany()
                        .HasForeignKey("NextYearFocusedSGframeworkNodeId");

                    b.Navigation("Evaluatee");

                    b.Navigation("Evaluator");

                    b.Navigation("FocusedFrameworkNode");

                    b.Navigation("FocusedSGFrameworkNode");

                    b.Navigation("FrameworkContext");

                    b.Navigation("ModifiedCompFocusedFrameworkNode2");

                    b.Navigation("NextYearFocusedFrameworkNode");

                    b.Navigation("NextYearFocusedSGframeworkNode");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidenceItem", b =>
                {
                    b.HasOne("SE.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId");

                    b.HasOne("SE.Domain.Entities.RubricRow", "RubricRow")
                        .WithMany()
                        .HasForeignKey("RubricRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.UserPromptResponse", "UserPromptResponse")
                        .WithMany()
                        .HasForeignKey("UserPromptResponseId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Observation");

                    b.Navigation("RubricRow");

                    b.Navigation("UserPromptResponse");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidencePackage", b =>
                {
                    b.HasOne("SE.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId");

                    b.HasOne("SE.Domain.Entities.RubricRow", "RubricRow")
                        .WithMany()
                        .HasForeignKey("RubricRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Observation");

                    b.Navigation("RubricRow");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidencePackageEvidenceItem", b =>
                {
                    b.HasOne("SE.Domain.Entities.EvidenceItem", null)
                        .WithMany("EvidencePackageEvidenceItems")
                        .HasForeignKey("EvidenceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.EvidencePackage", "EvidencePackage")
                        .WithMany("EvidencePackageEvidenceItems")
                        .HasForeignKey("EvidencePackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EvidencePackage");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkContext", b =>
                {
                    b.HasOne("SE.Domain.Entities.Framework", "DefaultFramework")
                        .WithMany()
                        .HasForeignKey("DefaultFrameworkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Role", "EvaluateeRole")
                        .WithMany()
                        .HasForeignKey("EvaluateeRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Framework", "InstructionalFramework")
                        .WithMany()
                        .HasForeignKey("InstructionalFrameworkId");

                    b.HasOne("SE.Domain.Entities.FrameworkContextPrototype", "PrototypeFrameworkContext")
                        .WithMany()
                        .HasForeignKey("PrototypeFrameworkContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Framework", "StateFramework")
                        .WithMany()
                        .HasForeignKey("StateFrameworkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefaultFramework");

                    b.Navigation("EvaluateeRole");

                    b.Navigation("InstructionalFramework");

                    b.Navigation("PrototypeFrameworkContext");

                    b.Navigation("StateFramework");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkContextPrototype", b =>
                {
                    b.HasOne("SE.Domain.Entities.Role", "EvaluateeRole")
                        .WithMany()
                        .HasForeignKey("EvaluateeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Framework", "InstructionalFramework")
                        .WithMany()
                        .HasForeignKey("InstructionalFrameworkId");

                    b.HasOne("SE.Domain.Entities.Framework", "StateFramework")
                        .WithMany()
                        .HasForeignKey("StateFrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluateeRole");

                    b.Navigation("InstructionalFramework");

                    b.Navigation("StateFramework");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkNode", b =>
                {
                    b.HasOne("SE.Domain.Entities.Framework", "Framework")
                        .WithMany("FrameworkNodes")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkNodeRubricRow", b =>
                {
                    b.HasOne("SE.Domain.Entities.FrameworkNode", "FrameworkNode")
                        .WithMany("FrameworkNodeRubricRows")
                        .HasForeignKey("FrameworkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.RubricRow", "RubricRow")
                        .WithMany("FrameworkNodeRubricRows")
                        .HasForeignKey("RubricRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameworkNode");

                    b.Navigation("RubricRow");
                });

            modelBuilder.Entity("SE.Domain.Entities.Observation", b =>
                {
                    b.HasOne("SE.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.User", "Evaluatee")
                        .WithMany()
                        .HasForeignKey("EvaluateeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Evaluation", "Evaluation")
                        .WithOne()
                        .HasForeignKey("SE.Domain.Entities.Observation", "EvaluationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Evaluatee");

                    b.Navigation("Evaluation");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("SE.Domain.Entities.PerceptionSurveyStatement", b =>
                {
                    b.HasOne("SE.Domain.Entities.RubricRow", "RubricRow")
                        .WithMany()
                        .HasForeignKey("RubricRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubricRow");
                });

            modelBuilder.Entity("SE.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SE.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SE.Domain.Entities.SchoolConfiguration", b =>
                {
                    b.HasOne("SE.Domain.Entities.FrameworkContext", "FrameworkContext")
                        .WithMany()
                        .HasForeignKey("FrameworkContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrameworkContext");
                });

            modelBuilder.Entity("SE.Domain.Entities.SelfAssessment", b =>
                {
                    b.HasOne("SE.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Evaluation", "Evaluation")
                        .WithOne()
                        .HasForeignKey("SE.Domain.Entities.SelfAssessment", "EvaluationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("SE.Domain.Entities.StudentGrowthGoal", b =>
                {
                    b.HasOne("SE.Domain.Entities.StudentGrowthGoalBundle", "GoalBundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.FrameworkNode", "FrameworkNode")
                        .WithMany()
                        .HasForeignKey("FrameworkNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.RubricRow", "ProcessRubricRow")
                        .WithMany()
                        .HasForeignKey("ProcessRubricRowId");

                    b.HasOne("SE.Domain.Entities.RubricRow", "ResultsRubricRow")
                        .WithMany()
                        .HasForeignKey("ResultsRubricRowId");

                    b.HasOne("SE.Domain.Entities.StudentGrowthGoalBundle", null)
                        .WithMany("Goals")
                        .HasForeignKey("StudentGrowthGoalBundleId");

                    b.Navigation("Evaluation");

                    b.Navigation("FrameworkNode");

                    b.Navigation("GoalBundle");

                    b.Navigation("ProcessRubricRow");

                    b.Navigation("ResultsRubricRow");
                });

            modelBuilder.Entity("SE.Domain.Entities.StudentGrowthGoalBundle", b =>
                {
                    b.HasOne("SE.Domain.Entities.Evaluation", "Evaluation")
                        .WithOne()
                        .HasForeignKey("SE.Domain.Entities.StudentGrowthGoalBundle", "EvaluationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserBuildingRole", b =>
                {
                    b.HasOne("SE.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.User", "User")
                        .WithMany("UserBuildingRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPromptGroupUserPrompt", b =>
                {
                    b.HasOne("SE.Domain.Entities.UserPromptGroup", "UserPromptGroup")
                        .WithMany("UserPromptGroupUserPrompts")
                        .HasForeignKey("UserPromptGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.UserPrompt", null)
                        .WithMany("UserPromptGroupUserPrompts")
                        .HasForeignKey("UserPromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPromptGroup");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPromptResponse", b =>
                {
                    b.HasOne("SE.Domain.Entities.UserPrompt", null)
                        .WithMany("Responses")
                        .HasForeignKey("UserPromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SE.Domain.Entities.WorkArea", b =>
                {
                    b.HasOne("SE.Domain.Entities.Role", "EvaluateeRole")
                        .WithMany()
                        .HasForeignKey("EvaluateeRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EvaluateeRole");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SE.Domain.Entities.WorkAreaContext", b =>
                {
                    b.HasOne("SE.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.FrameworkContext", "FrameworkContext")
                        .WithMany()
                        .HasForeignKey("FrameworkContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.User", "User")
                        .WithMany("WorkAreaContexts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE.Domain.Entities.WorkArea", "WorkArea")
                        .WithMany()
                        .HasForeignKey("WorkAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("FrameworkContext");

                    b.Navigation("User");

                    b.Navigation("WorkArea");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidenceItem", b =>
                {
                    b.Navigation("EvidencePackageEvidenceItems");
                });

            modelBuilder.Entity("SE.Domain.Entities.EvidencePackage", b =>
                {
                    b.Navigation("EvidencePackageEvidenceItems");
                });

            modelBuilder.Entity("SE.Domain.Entities.Framework", b =>
                {
                    b.Navigation("FrameworkNodes");
                });

            modelBuilder.Entity("SE.Domain.Entities.FrameworkNode", b =>
                {
                    b.Navigation("FrameworkNodeRubricRows");
                });

            modelBuilder.Entity("SE.Domain.Entities.RubricRow", b =>
                {
                    b.Navigation("FrameworkNodeRubricRows");
                });

            modelBuilder.Entity("SE.Domain.Entities.StudentGrowthGoalBundle", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SE.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserBuildingRoles");

                    b.Navigation("WorkAreaContexts");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPrompt", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("UserPromptGroupUserPrompts");
                });

            modelBuilder.Entity("SE.Domain.Entities.UserPromptGroup", b =>
                {
                    b.Navigation("UserPromptGroupUserPrompts");
                });
#pragma warning restore 612, 618
        }
    }
}
